managerNode:
  host: "192.168.40.128"
  port: 3306
  user: "admin"
  password: "123456"
  database: "test"
  charset: "utf8"
cliNodes:
  -
    host: "192.168.40.128"
    port: 3306
    user: "admin"
    password: "123456"
    database: "information_schema"
    charset: "utf8"
    binlogfile: "mysql-bin.000001"
    binlogpos: 4
    autopos: false
#  -
#    host: "192.168.40.1282"
#    port: 3306
#    user: "user"
#    password: "123456"
#    database: "test"
#    charset: "utf8"
#    binlogfile: "mysql-bin.000001"
#    binlogpos: 4
#    autopos: true